name = "houston-registry"
main = "src/index.ts"
compatibility_date = "2024-05-12"

routes = [
  { pattern = "store.gethouston.ai", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "houston-registry"
database_id = "d5082cfd-bcb0-4c3d-9bb5-6f7967a349e9"
